#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$LENT_PROJECT" != "" ]; 
then
    # Build googletest

    LENT_THIRD_PARTY=$LENT_PROJECT/third-party
    mkdir -p $LENT_THIRD_PARTY

    echo "Building Google Test..." 

    if [ ! -d $LENT_THIRD_PARTY/googletest ];
    then
        echo "git clone https://github.com/google/googletest.git  $LENT_THIRD_PARTY/googletest" 
        git clone https://github.com/google/googletest.git  $LENT_THIRD_PARTY/googletest
    #else
        #echo "Pulling changes from https://github.com/google/googletest.git"
        #cd $LENT_THIRD_PARTY/googletest
        #git pull
        #cd $LENT_PROJECT
    fi

    LENT_GOOGLE_TEST=$LENT_THIRD_PARTY/googletest/googletest
    LENT_GOOGLE_TEST_BUILD=$LENT_GOOGLE_TEST/build

    if [ ! -d $LENT_GOOGLE_TEST_BUILD ]; 
    then
        mkdir $LENT_GOOGLE_TEST_BUILD
    fi

    cd $LENT_GOOGLE_TEST_BUILD
    cmake -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON -G"Unix Makefiles" $LENT_GOOGLE_TEST

    make
    cd $LENT_PROJECT

    printf "Done building Google Test.\n\n"

    # Build lent
    echo "Building LENT..."
    if [ "$WM_PROJECT_DIR" != "" ]; 
    then
        src/Allwmake
        applications/Allwmake
        printf "Done building LENT.\n\n"
    else
        echo "OpenFOAM is not configured properly. Source the project's etc/bashrc file." 
    fi
else
    echo "The LENT project is not configured properly. Source the project's etc/bashrc file." 
fi
 


