#!/usr/bin/python2

import numpy as np
import sys

from matplotlib import pyplot as plt
from matplotlib import rc
from matplotlib.font_manager import FontProperties

rc('text', usetex=True)

def plot_velocity_errors(francois_file, norm):

    # Read errors
    errorsFrancois = np.loadtxt(francois_file)
    errorsLent = np.loadtxt("francois-velocity-errors.dat")

    fig = plt.figure(figsize=(8, 8))

    plt.loglog()
    plt.xlabel(r"$h$")
    if norm == "L1":
        plt.ylabel(r"$L_1(\mathbf{u})$")
        column = 2
    elif norm == "L2":
        plt.ylabel(r"$L_2(\mathbf{u})$")
        column = 3
    elif norm == "Linf_simple" or norm == "Linf_kernel":
        plt.ylabel(r"$|\mathbf{u}|_{max}$")
        column = 4

    # Plot values from Francois Paper
    if (len(errorsFrancois[0:4,0]) > 0):
        plt.plot(errorsFrancois[0:4,0], errorsFrancois[0:4,1], marker='s', label=r"CSF with convolution $d=1.9h^{0.5}$")
    if (len(errorsFrancois[4:8,0]) > 0):
        plt.plot(errorsFrancois[4:8,0], errorsFrancois[4:8,1], marker='o', label=r"CSF with height function")
    if (len(errorsFrancois[8:12,0]) > 0):
        plt.plot(errorsFrancois[8:12,0], errorsFrancois[8:12,1], marker='*', label=r"SSF with convolution $d=1.9h^{0.5}$")
    if (len(errorsFrancois[12:16,0]) > 0):
        plt.plot(errorsFrancois[12:16,0], errorsFrancois[12:16,1], marker='^', label=r"SSF with height function")

    # Plot lent errors
    plt.plot(errorsLent[:,0], errorsLent[:,column], marker='>', label=r"LENT M-N02")

    lgd = plt.legend(loc='center right', bbox_to_anchor=(1.5, 0.5), fancybox=True, shadow=True)

    plt.savefig("francois-velocity-fig14_" + norm + ".pdf", bbox_extra_artists=(lgd,),bbox_inches='tight')

#-----------------------------------------------------------------------------
def main():
    print ("Plotting velocity error diagrams...");
    plot_velocity_errors("francois-velocity-fig14a.csv", "L1");
    plot_velocity_errors("francois-velocity-fig14b.csv", "L2");
    plot_velocity_errors("francois-velocity-fig14c.csv", "Linf_simple");
    plot_velocity_errors("francois-velocity-fig14d.csv", "Linf_kernel");
    print ("Done")

if __name__ == '__main__': main()
