#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export CXXFLAGS=$WM_CXXFLAGS

export LENT_PROJECT=${DIR%%/etc*}

export PATH=$LENT_PROJECT/src/scripts:$LENT_PROJECT/src/scripts/verification:$PATH
export LD_LIBRARY_PATH=$LENT_PROJECT/third-party/googletest/googletest/build:$LD_LIBRARY_PATH


