#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LENT_GCC_OPTIONS="-std=c++2a -Wno-deprecated-copy"

export LENT_PROJECT=${DIR%%/etc*}

export PATH=$LENT_PROJECT/src/scripts:$LENT_PROJECT/src/scripts/verification:$PATH

export LENT_GTEST_LIB="$LENT_PROJECT/third-party/googletest/googletest/build/lib"
export LENT_GTEST_INC="$LENT_PROJECT/third-party/googletest/googletest/include/gtest"

export LD_LIBRARY_PATH=$LENT_GTEST_LIB:$LD_LIBRARY_PATH
export PYTHONPATH="$LENT_PROJECT/src/scripts":$PYTHONPATH

# PC/laptop
export EIGEN_HEADERS=/usr/include/eigen3

# LICHTENBERG CLUSTER: module load eigen/3.3.7 
#export EIGEN_HEADERS=/shared/apps/.gcc/9.2/eigen/3.3.7
