#!/usr/bin/bash

# Description
# Clear all OpenFOAM cases in subdirectories (recursive).

# Authors
# Tomislav Maric tomislav<<dot>>maric<<a>>gmx<<dot>>com

. verificationFunctions 

TARGET_DIR=$1
EXCLUDED_CASES=$2

if [ ! -d $TARGET_DIR ];
then
    TARGET_DIR=$(pwd)
fi

clear_cases $TARGET_DIR "$EXCLUDED_CASES"
