#!/usr/bin/bash

# Description
# Script for automatical verification of the lent algorithm.

# Authors
# Tomislav Maric tomislav<<dot>>maric<<a>>gmx<<dot>>com

. verificationFunctions 

foamClearCasesRecursive

generate_meshes "32 64 128"

run_cases "lentReconstruct" "32 64 128"

#collect_tet_case_data(tet)
#create_test_reports(tet)
