#!/usr/bin/bash

# Description
# Script for automatical verification of the lent algorithm.

# Authors
# Tomislav Maric tomislav<<dot>>maric<<a>>gmx<<dot>>com

. verificationFunctions 


if found_pattern "hex-0128" "128 tet";
then
    echo FOUND
else
    echo NOT FOUND
fi

#clear_cases "hex" 
#clear_cases "tet"
#clear_cases "poly" 

#generate_meshes "hex"
#generate_meshes "tet"
#generate_meshes "poly"

#collect_tet_case_data(tet)
#create_test_reports(tet)
